### ISSUE TITLE
When the configured threshold is reached the problem should bubble up

### ISSUE THREAD

**Issue by DerAlbertCom** [matkoch/resharper-cognitivecomplexity#1]
if a method is complex, then the info shows up in the code vision, that's not wrong at all. but it is hard to discover problematic methods in a solution. Because this is manual work, have to check every method.

It would be nice if this could popup as a warning in the solution wide analysis with a configurable severity.

**Comment by matkoch** [comment]
it does from the  latest version

**Comment by DerAlbertCom** [comment]
So, i must open an Rider Issue that the Plug In Update was not visible to me ;)
