### ISSUE TITLE
Error Installing 2019.3.1

### ISSUE THREAD

**Issue by Mike-EEE** [matkoch/resharper-cognitivecomplexity#10]
FWIW, I had an error while installing this extension, the details of which can be found here:

https://youtrack.jetbrains.com/issue/RSRP-477617

Posting here for maximum awareness. :)

**Comment by udlose** [comment]
I also have the same problem.

**Comment by matkoch** [comment]
but does it work though?

**Comment by udlose** [comment]
@matkoch it does not work. There is nothing for this extension displayed above any method.  And I have restarted VisualStudio).

The only thing I see related to the extension is that it is listed in Resharper's Code Inspection settings.  Selecting the 'Cognitive Complexity' item doesn't display the settings (assuming it has some- if not, it should at least mention that it doesn't have any).

![image](https://user-images.githubusercontent.com/656118/71855503-d1c0cf80-30a6-11ea-9334-29866293ee21.png)

**Comment by matkoch** [comment]
Okay, I was confused about how you could even install the extension. That shouldn't have been possible. Nevermind,  2019.3.1 is uploaded now.

**Comment by udlose** [comment]
@matkoch - improved but still not working.  So after uninstalling the previous version and installing the new 2019.3.1, I can now see the settings in the Resharper Options:

![image](https://user-images.githubusercontent.com/656118/71909549-e5674700-3135-11ea-8033-cbeba933e8a5.png)

However, I still don't see any difference in the information displayed by CodeLens above my methods than what was there before installing the extension:

![image](https://user-images.githubusercontent.com/656118/71909746-3d05b280-3136-11ea-9427-db2f72d18fc3.png)

**Comment by matkoch** [comment]
There is nothing shown in CodeLens. Only in Rider.

**Comment by udlose** [comment]
So this extension does not work for VisualStudio 2019?

**Comment by matkoch** [comment]
It does, but only via tooltips and code inspections (squiggles) when the threshold was exceeded.

**Comment by udlose** [comment]
Ok, I can see the toolip now.  Will there be an update coming to have it display all the time as is shown on the main page for the extension?

**Comment by matkoch** [comment]
Unfortunately, no. ReSharper doesn't support extending Visual Studio CodeLens.

**Comment by matkoch** [comment]
@udlose maybe try Rider and let me know if you miss something :)

**Comment by Mike-EEE** [comment]
I myself would try Rider but am waiting on guidance per the comments here, @matkoch:

https://youtrack.jetbrains.com/issue/RIDER-19398

😁
