### ISSUE TITLE
Complexity does not show for expression-bodied methods

### ISSUE THREAD

**Issue by Tdue21** [matkoch/resharper-cognitivecomplexity#13]
Although it may make some kind of sense, the complexity does not seem to be calculated for expression-bodied methods. It does not show in any event. 

Example: 
```
public async Task<List<ServerTypeDto>> ListServerTypes(CancellationToken cancellationToken)
{
            return await _unitOfWorkFactory.Create()
                                           .GetRepository<ServerType>()
                                           .Query
                                           .Select(item => item.ToDto())
                                           .ToListAsync(cancellationToken);
}
```
This shows a complexity of 0. Which, by the way, tells me that LINQ method chains may not be evaluated... 

But if I refactor this method to an expression body, like this: 
```
public async Task<List<ServerTypeDto>> ListServerTypes(CancellationToken cancellationToken) =>
           await _unitOfWorkFactory.Create()
                                   .GetRepository<ServerType>()
                                   .Query
                                   .Select(item => item.ToDto())
                                   .ToListAsync(cancellationToken);

```
No complexity is shown at all.

**Comment by nick-morhun** [comment]
As the documentation says, "complexity" is calculated based on the control flow operators. There are no operators here, so no "complexity".

**Comment by Tdue21** [comment]
Ok. But how about any control flow inside a Linq method? Will they be counted?

**Comment by matkoch** [comment]
@Tdue21 I don't think it makes sense to show them for statement lambdas because those don't have any of the other CodeVision items shown, like last author, usages, or anything else.
