### ISSUE TITLE
No info shown and missing configs

### ISSUE THREAD

**Issue by KevinGelking** [matkoch/resharper-cognitivecomplexity#14]
VS Community 2019 - v16.6.1
ReSharper Ultimate 2020.1.3
CognitiveComplexity 2020.1.0

My problem is, that there is no info shown at all, as if the plugin was not active. There are also missing config entries that should be present~

Here's a screenshot of sample code that should show the complexity:
![image](https://user-images.githubusercontent.com/30538130/84021351-b70bc300-a984-11ea-8b49-1e305db40014.png)

Here's a screenshot of the config, which does not show the extra 3 lines that should appear based on the github repo description.
![image](https://user-images.githubusercontent.com/30538130/84021037-3056e600-a984-11ea-8b85-2d7f3cd03aa3.png)

**Comment by KevinGelking** [comment]
Nevermind. I figured this out from a separate issue which had already been closed. I do get the inspection, but it's hidden behind a mouse-hover tooltip, which sadly makes the extension rather useless. I do hope ReSharper eventually integrates into code-lens so we can get Rider-like behaviour.

Perhaps the info page can be adjusted to avoid confusion between the Rider and ReSharper version? The visibility is fundamentally different.

**Comment by matkoch** [comment]
You still get the warning if the threshold is exceeded. But true,
integration with Code Lens would be nice :)

**Comment by KevinGelking** [comment]
As for my issue, I suppose that’s resolved, as it is not currently possible to implement.
I’m testing out Rider on trial now, though, so I can take full advantage of the plugin.

**Comment by matkoch** [comment]
Okay. Let me know if you have any other questions. Also regarding Rider :)
