### ISSUE TITLE
Add Whole Project/Sln Analysis 

### ISSUE THREAD

**Issue by MutatePat** [matkoch/resharper-cognitivecomplexity#22]
I think it would be beneficial to introduce a screen in the plugin to view a breakdown of Cognitive Complexity across a whole project/solution :- this will help to identify key areas for refactoring.

**Comment by matkoch** [comment]
Sorry, but that's out of scope at least on my end. What you can do is running code analysis against this exact inspection, and then group the results by project. However, we can't provide a "solution or project value".

**Comment by MutatePat** [comment]
> Sorry, but that's out of scope at least on my end. What you can do is running code analysis against this exact inspection, and then group the results by project. However, we can't provide a "solution or project value".

Thanks, where can I set the exact inspection when I run code inspection?

**Comment by matkoch** [comment]
At least in Rider you should be able to find “Run Inspection” from the
actions menu. Then search for cognitive complexity.
