### ISSUE TITLE
CognitiveComplexity doesn't work in resharper 2021.1.2

### ISSUE THREAD

**Issue by MbarkT3STO** [matkoch/resharper-cognitivecomplexity#23]
The problem start from upgrading rom `resharper` 2020.3 to 2021.1 the tab in options was hidden and when hover on my methods I do not see any cognitive

Please any help?

**Comment by matkoch** [comment]
is the version of the plugin also 2021.1 ? i just tried, and it works

**Comment by MbarkT3STO** [comment]
I installed it, version 2021.1 but not displayed statistic when hover on a method and doesn't shown in the resharper's settings
Please help

**Comment by matkoch** [comment]
Did you restart Visual Studio? Have you tried reinstalling the plugin?

**Comment by MbarkT3STO** [comment]
I'ts working now after enable **Title** in features options
