### ISSUE TITLE
After installing in Rider 2022.1 EAP3, Code Vision location is not according to configuration

### ISSUE THREAD

**Issue by mterwoord** [matkoch/resharper-cognitivecomplexity#28]
I'm used to having all the code vision elements next to a method as opposed to before the line. This used to work fine, but with the EAP version, it suddenly doesn't work.
I do have it set in the settings.

**Comment by matkoch** [comment]
Could you provide a couple of before/after screenshots?

**Comment by mterwoord** [comment]
See below.
I now realize that this may be a Rider issue, but still, the others are ok.
Please let me know if this helps. (Some positive note: Awesome plugin!)


**Eap**:
![image](https://user-images.githubusercontent.com/114143/156426102-f136a3e8-b2d5-4114-b68d-67aae107ab75.png)
Settings:
![image](https://user-images.githubusercontent.com/114143/156426330-a7806420-3082-4fba-a932-f90abeb0af60.png)


**Latest RTM**:
![image](https://user-images.githubusercontent.com/114143/156426230-ba8fb99d-7fe4-4cbe-9088-f9ca83507b3d.png)
Settings:
![image](https://user-images.githubusercontent.com/114143/156426388-ecd92ff7-9686-493b-8c26-d8148c5c5376.png)

**Comment by matkoch** [comment]
Please try again with EAP5

**Comment by mterwoord** [comment]
With latest EAP (5) of rider, and eap3 version of this plugin, the issue still persists.

**Comment by mterwoord** [comment]
I _think_ this is in fact a rider bug, see https://youtrack.jetbrains.com/issue/RIDER-75672

Will keep you informed.

**Comment by mtone** [comment]
Fixed for me in 2022.1 EAP9.
