### ISSUE TITLE
Change classification of problem

### ISSUE THREAD

**Issue by m-jepson** [matkoch/resharper-cognitivecomplexity#3]
The problems found by this extension are classified as `WarningHighlighting`. This means that this is the comment to disable it once:

`// ReSharper disable once WarningHighlighting`

Also, inspectcode.exe (running on our build server) outputs issues into XML as `WarningHighlighting` issues.

It would be nice if these were classified as `CognitiveComplexity`.

**Comment by matkoch** [comment]
Good point. I'll check on this later!

**Comment by matkoch** [comment]
This is fixed with 2019.2.0
