### ISSUE TITLE
Find all methods that are complex (i.e above threshhold)

### ISSUE THREAD

**Issue by nikbra** [matkoch/resharper-cognitivecomplexity#32]
Hi

Maybe it is just me not finding or know how to do. Really like the plugin.
I'm new to Rider.
Can complex methods be found in a solution and listed ?

//Regards

**Comment by matkoch** [comment]
From an existing warning you can find all issues in the solution:

<img width="1025" alt="JetBrains Rider-nuke-common – BuildManager cs-2023-02-15-Nqs02zft@2x" src="https://user-images.githubusercontent.com/5005566/219206890-f5537f69-f697-4d47-a2fa-95cba8baae52.png">

With the `Run inspection by name` action, you can also search for the warning:

<img width="606" alt="JetBrains Rider-nuke-common – BuildManager cs-2023-02-15-PFqTcpex@2x" src="https://user-images.githubusercontent.com/5005566/219206927-42c32365-f438-462f-9dbf-eb01547e4d8d.png">
