### ISSUE TITLE
Is not compatible with 2023.1.1

### ISSUE THREAD

**Issue by gaydenko** [matkoch/resharper-cognitivecomplexity#33]
As subject says

**Comment by matkoch** [comment]
Need more information. The current version is still marked as compatible and it also does work locally for me.

<img width="532" alt="Microsoft Edge-Update Details - CognitiveComplexity 2023 1 0  JetBrains Marketplace-2023-05-11-KWg7m8CE@2x" src="https://github.com/matkoch/resharper-cognitivecomplexity/assets/5005566/52f82302-e171-46ef-be1b-e2492128bac8">
<img width="806" alt="JetBrains Rider-Settings-2023-05-11-xA7Jw4eV@2x" src="https://github.com/matkoch/resharper-cognitivecomplexity/assets/5005566/f8175137-6509-40db-bd2a-3fbc8c5d90f4">
