### ISSUE TITLE
[Bug] Does not show colors in Rider IDE and settings missing

### ISSUE THREAD

**Issue by sgrigsoftserve** [matkoch/resharper-cognitivecomplexity#35]
When using this Plugin in RIder IDE two things are missing:

- there are no colors depending on the complexity, it just stays transparent
- the settings showed in the plugin page are not available in Rider Settings

![image](https://github.com/matkoch/resharper-cognitivecomplexity/assets/118432934/a127b797-e504-4496-8751-91dea9cce7a9)

![image](https://github.com/matkoch/resharper-cognitivecomplexity/assets/118432934/48ed9aa1-45c8-4f52-9584-3977e2e1473a)
![image](https://github.com/matkoch/resharper-cognitivecomplexity/assets/118432934/77490dbd-1ebd-469a-a5b8-3780159388c6)
![image](https://github.com/matkoch/resharper-cognitivecomplexity/assets/118432934/34b4b5a1-1c33-468c-b8df-4151fd69c7f9)

OS: `Windows 10`
Rider version:  `2023.1.1, Build #RD-231.8770.54, built on April 25, 2023`
CognitiveComplexity version: `2023.1.0`

**Comment by iploooox** [comment]
@matkoch Experiencing the same, it doesn't show anything. i have reinstalled it twice.

OS: Mac OS 13.0.1
Rider version: 2023.1.3 Build #RD-231.9161.46, built on June 21, 2023
CognitiveComplexity version: 2023.1.0

![image](https://github.com/matkoch/resharper-cognitivecomplexity/assets/115003487/cdf352fd-f92f-412c-a4aa-462c32a41c5e)

**Comment by matkoch** [comment]
@iploooox I don't see anything wrong from your screenshot. Options page is there, and diamond symbol above method as well.
