### ISSUE TITLE
Using logger wrapper ahead method's logic offs plugin calculation

### ISSUE THREAD

**Issue by Tyomios** [matkoch/resharper-cognitivecomplexity#37]
Our team use such method format:  `private async Task Method() => 
        _logger.LogOperation(
        new(),
        async () =>
        {
            Common code
        });`

Please, add some of config of plugin, to have an opportunity set method's format.

**Comment by matkoch** [comment]
I'm sorry, but it's rather unclear what you're asking for

**Comment by matkoch** [comment]
Feel free to come back with more information later. For now I will close this.
