### ISSUE TITLE
"Sample Highlighting Message" Issue

### ISSUE THREAD

**Issue by dprice** [matkoch/resharper-cognitivecomplexity#4]
After installing the latest Rider 2019.2 EAP5, I started seeing highlighted code everywhere with a tooltip that says "Sample Highlighting Message" in any C# file on method names, parameter names, private variables, etc. JetBrains support helped me track it down to your plugin.

I've disabled for now but thought you should know about the issue.

Thanks,
Derek

**Comment by matkoch** [comment]
Hi Derek, my bad, thanks!

**Comment by matkoch** [comment]
Fixed with 2019.2.1
