### ISSUE TITLE
No hints in ReSharper 2024.3 (and VS 17.12)

### ISSUE THREAD

**Issue by taurit** [matkoch/resharper-cognitivecomplexity#40]
Hi Matthias!

I wanted to check the CognitiveComplexity plugin after seeing it yesterday in Warsaw's .NET group (thanks for the great talk, by the way!).

The extension has been installed with no errors, and I can see the configuration panel but no hints in the editor. In the past, I disabled inlay hints and CodeLens, but re-enabling them didn't solve the issue.
![obraz](https://github.com/user-attachments/assets/c87ce79c-15ac-4675-a87f-96f76cddf337)

Is CognitiveComplexity 2024.3 known to be compatible/incompatible with the current R#/VS versions yet?

## Versions used
I use the most recent stable versions of everything: 
![obraz](https://github.com/user-attachments/assets/85ca1ab7-95e2-4fa8-b217-07a37f2d9fd8)
![obraz](https://github.com/user-attachments/assets/e740c5c3-b099-4335-8961-f8a559c581f0)
![obraz](https://github.com/user-attachments/assets/e7812193-a79e-429b-87d1-b5521baa0284)

**Comment by matkoch** [comment]
Hi Tim! (Thanks:))

The CodeVision items (aka CodeLens) are only available in the Rider plugin, unfortunately. The ReSharper plugin will only add warnings based on the threshold.

**Comment by Luk164** [comment]
For anyone that ends up looking for something similar I found this old but still working extension: https://github.com/tackme31/howmessy
