### ISSUE TITLE
Show complexity in tooltip even when threshold is not exceeded

### ISSUE THREAD

**Issue by aboy021** [matkoch/resharper-cognitivecomplexity#6]
It would be great if the complexity of a method could be viewed by looking at its tooltip in Visual Studio.
This is the approach used by the [cyclomatic complexity plugin](https://github.com/JetBrains/resharper-cyclomatic-complexity).

**Comment by kstreichergb** [comment]
Doesn't it do that already?
![image](https://user-images.githubusercontent.com/50991928/68744581-3a368780-05f5-11ea-9b64-7d206e0e8632.png)

**Comment by BradKnowles** [comment]
I'm also not seeing the information in the tooltip.  I'm running Visual Studio 2019 Professional 16.3.9 and ReSharper Ultimate 2019.2.3

Here is my method showing a tooltip (I also have the Cyclomatic Complexity Plugin)

![image](https://user-images.githubusercontent.com/1277856/69351012-9d08ce00-0c48-11ea-9981-fa2eeddc9076.png)

My settings
![image](https://user-images.githubusercontent.com/1277856/69351116-c3c70480-0c48-11ea-8cdb-c53331050e68.png)

**Comment by matkoch** [comment]
It doesn't really make sense to have both installed. Can you try again with CyclomaticComplexity plugin uninstalled?

**Comment by matkoch** [comment]
BTW, the tooltip is only shown when the threshold is exceeded. I don't really see a point in displaying it otherwise.

**Comment by BradKnowles** [comment]
Makes sense on both accounts, I already had the Cyclomatic Complexity plugin installed when I decided to try it out.  It's been uninstalled.

Based on the settings in the previous screen shot, the tooltip should appear if the complexity exceeds 8% and should say "Simple Enough" between 8 and 79%?

I'm still not seeing it appear in the tooltip.  Is my test method not complex enough?

![image](https://user-images.githubusercontent.com/1277856/69503404-4a156c00-0f11-11ea-9371-20ef2eec6937.png)

**Comment by matkoch** [comment]
Sorry I wasn’t clear enough. The tooltip/inspection appears when the language threshold is exceeded. Here it’s 8, but not 8% but 8 as a scalar value.

**Comment by aboy021** [comment]
Thanks for clearing that up. I can confirm that it works as you've described for me.

Turns out what I'd really like is the option to always show the measured complexity in the tooltip.
Thank you.

**Comment by matkoch** [comment]
I think last time I tried I had some issues, but I will look at it again.

**Comment by aboy021** [comment]
Awesome. In either case it's a wonderful extension.

**Comment by programuotojasgf** [comment]
doesn't show anything on Visual studio for me, even with every setting set to 0.

**Comment by matkoch** [comment]
Not sure what you mean. In visual studio there’s only one setting available.

**Comment by programuotojasgf** [comment]
![image](https://user-images.githubusercontent.com/1044735/69618901-5ac5ff00-1043-11ea-99d0-fce64b1b7276.png)

**Comment by programuotojasgf** [comment]
![image](https://user-images.githubusercontent.com/1044735/69618983-7fba7200-1043-11ea-83f4-0499e49817d2.png)

**Comment by matkoch** [comment]
I need glasses.

**Comment by matkoch** [comment]
@programuotojasgf it's a different issue though if you don't see the tooltip even when the threshold is exceeded. Please create a new one.

**Comment by matkoch** [comment]
FIxed with 2019.3.1
