### ISSUE TITLE
Can not see the tooltip even when threshold exceeded

### ISSUE THREAD

**Issue by programuotojasgf** [matkoch/resharper-cognitivecomplexity#7]
Settings are so that all the thresholds are at 0. No complexity is shown. 
VS 16.3.10
ReSharper 2019.2.2
CognitiveComplexity 2019.2.2

![image](https://user-images.githubusercontent.com/1044735/69626108-a16e2600-1050-11ea-862b-a3cfb013a958.png)

**Comment by matkoch** [comment]
Can you please provide a repo with the dotsettings checked-in as well?

**Comment by programuotojasgf** [comment]
Do you mean a solution with this issue as a separate fork?

**Comment by matkoch** [comment]
Please try 2019.3.1

**Comment by programuotojasgf** [comment]
fixed!
