### ISSUE TITLE
Problem with plugin theme in Rider 2019.3

### ISSUE THREAD

**Issue by rafek1241** [matkoch/resharper-cognitivecomplexity#8]
![image](https://user-images.githubusercontent.com/9272027/71192192-174c6280-2288-11ea-80d8-206e63071d71.png)

The black boxes after methods show this `+1` information but they are not visible. (all black). They are readable only with light theme which I don't use.

**Comment by matkoch** [comment]
Fixed with 2019.3.2 which will be published soon.
