### ISSUE TITLE
Calculate on aggregate

### ISSUE THREAD

**Issue by DustinZeimet** [matkoch/resharper-cognitivecomplexity#9]
One of the benefits listed in the G. Ann Campbell paper was that this method allows for aggregate calculations to be useful. Would be excellent to see sums of complexity at the top of each class as well as a report to see the most complex classes.

**Comment by matkoch** [comment]
comparing the required effort (and risk) to the rather little gain, i’m afraid this is not going to happen from my side. thanks for the suggestion though.
